### ISSUE TITLE
Stream audio plays out of phone speakers

### ISSUE THREAD

**Issue by clone1018** [Glimesh/glimesh_app#22]
When watching a stream on Android, the audio plays out of the phone's speakers instead of the speakerphone speakers. Meaning the user has to put the phone up next to their face to hear the stream.

**Comment by danstiner** [comment]
Can confirm this is due to the webrtc framework. In java land it is possible to override the usage type to be `MEDIA` which fixes the issue: https://github.com/danstiner/glimdroid/blob/main/app/src/main/java/com/danielstiner/glimdroid/ui/channel/ChannelActivity.kt#L505

I don't think the flutter webrtc wrapper lib let's you set the usage though, might have to send a PR to them to update the library before this can be fixed.

**Comment by clone1018** [comment]
Dove down the rabbit hole a bit today, seems super complex. I did find code that should be switching to bluetooth automatically if a headset is available: https://cs.github.com/flutter-webrtc/flutter-webrtc/blob/a0ca458e4fafa5599702ed318552b2be0adae1fc/android/src/main/java/com/cloudwebrtc/webrtc/utils/RTCAudioManager.java#L467

There's so many layers here though, it's unclear what changes would need to be made to switch the media type.

**Comment by ponkey364** [comment]
I also did some digging on this, then completely forgot to post what I found, I have no clue if this will work, since I am really not an android or Java person, have no way to test this on real hardware and even then, there's still the possibility the below won't fix it.
The flutter-webrtc folks seem to believe this is an issue with the webrtc library, which it isn't, as Dan is doing it fine (maybe it was back in 2020 when the issues were posted). Because of the above, I'm thinking forking is going to be the only way forward (also I'd have no clue how to implement the equivalent API on iOS).

From pretty much grepping over their codebase (from the 0.7.1 tag, as newer caused issues with the limited testing i have been able to do, although the code referenced below hasn't changed since then and is the same on master), I wonder if we could replace the code in flutter-webrtc's `android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java` file, specifically lines 149-153, the `JavaAudioDeviceModule.builder` bits with Dan's 502-508 (oh and I think we'd have to put an import for `android.media.AudioAttributes` at the top too)?

**Comment by clone1018** [comment]
Links for convenience: 

flutter-webrtc: https://github.com/flutter-webrtc/flutter-webrtc/blob/9b928ce5040dc832a240f2cc888071cc173ae96a/android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java#L149-L153
glimdroid: https://github.com/danstiner/glimdroid/blob/343402b441cd59d2ce85a38ce2d3fc970317ac1d/app/src/main/java/com/danielstiner/glimdroid/ui/channel/ChannelActivity.kt#L502-L508

**Comment by clone1018** [comment]
I think this sounds like a good approach. Do you want to try the fork / modifications, or do you want me to? I have access to an Android phone, but I can't get it working with dev so I'd likely need to deploy it to our alpha channel either way!

**Comment by ponkey364** [comment]
I'll have a look today, will fork flutter-webrtc to my account, then if this works we can figure out the next steps

**Comment by ponkey364** [comment]
I've pushed branch android-audio-botch to this repo, and glim-botch to ponkey364/flutter-webrtc, not sure if you want to pull the branch and try (maybe also remove the call to _setupSpeakerphone since I'm not sure how that affects it?)

**Comment by clone1018** [comment]
Looks like this works great on Android, I opened up a PR to fix the syntax a bit though (wouldn't build at first). https://github.com/ponkey364/flutter-webrtc/pull/1

Should we make a new fork, or move yours over to the Glimesh org?

**Comment by ponkey364** [comment]
Merged the PR, made some comments there but I'll put them here too:
there may be some changes required over here as part of updating to the latest version of flutter-webrtc (i think cocoapods got upset when I tried it) and also we'll have to remove the ref: glim-botch from pubspec.yaml so we get the corrected version.

I'll DM you on discord about transferring the repo.

**Comment by clone1018** [comment]
I don't think I meant to target main, but if that's a problem we can merge the changes into the botch branch. Either way once you get it sorted I'll test android again to be sure.
